spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev_db
    username: tmp
    password: dummy
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
